# Generated by Django 5.1.1 on 2024-10-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0003_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
