# Generated by Django 5.1.1 on 2024-10-19 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0004_alter_search_keyword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
