# Generated by Django 5.1.1 on 2024-12-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0008_product_sales_count_product_stock_purchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_restock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='restock_amount',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='restock_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
